[application]
name = "lostdisplay" # App name
default_platform = "web" # The Dioxus platform to default to
out_dir = "dist" # `build` & `serve` output path
asset_dir = "public" # The static resource path

[web.app]
title = "lostdisplay.space" # HTML title tag content

[web.watcher]
reload_html = true # When watcher is triggered, regenerate the `index.html`
watch_path = ["src", "public", "assets"] # Which files or dirs will be monitored

# Include style or script assets
[web.resource]
style = ["/tailwind.css"]
script = []

[web.resource.dev]
style = []
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"

